Fix route ownership breaking with spam routes.
Last night the bq cron email reporter failed with this
error:
```
Traceback (most recent call last):
  File "/home/ubuntu/internal-webserver/gae_dashboard/email_bq_data.py", line 963, in <module>
    main()
  File "/home/ubuntu/internal-webserver/gae_dashboard/email_bq_data.py", line 944, in main
    email_instance_hours(date, dry_run=args.dry_run)
  File "/home/ubuntu/internal-webserver/gae_dashboard/email_bq_data.py", line 452, in email_instance_hours
    for initiative_id, initiative_data in _by_initiative(data):
  File "/home/ubuntu/internal-webserver/gae_dashboard/email_bq_data.py", line 64, in _by_initiative
    teams = f(row[key])
  File "/home/ubuntu/internal-webserver/gae_dashboard/initiatives.py", line 143, in route_owners
    for name in match.groups():
AttributeError: 'NoneType' object has no attribute 'groups'
```

This is because sometimes spam requests with weird URLs results in elog_url_routes that don't match
our route spec.

This fix ignores those routes.

I made a similar change in D54587.

Test Plan: `python email_bq_data.py --date=20190523 --dry-run`

Auditors: andrew, boris, alexshah