Retry twice if the gae-dashboard url-fetch fails.
Summary:
We saw some periodic errors on June 1:

    Traceback (most recent call last):
      File "/home/ubuntu/internal-webserver/gae_dashboard/ka_report.py", line 126, in <module>
        main()
      File "/home/ubuntu/internal-webserver/gae_dashboard/ka_report.py", line 117, in main
        version=args.version)
      File "/home/ubuntu/internal-webserver/gae_dashboard/gae_dashboard_scrape.py", line 100, in scrape
        cache[parser_key] = parser_class(dashclient.fetch(url))
      File "/home/ubuntu/internal-webserver/gae_dashboard/gae_dashboard_curl.py", line 48, in fetch
        return fetch_contents(self.rpcserver, url)
      File "/home/ubuntu/internal-webserver/gae_dashboard/gae_dashboard_curl.py", line 96, in fetch_contents
        return rpcserver.Send(request_path, None)
      File "/usr/local/google_appengine/google/appengine/tools/appengine_rpc.py", line 391, in Send
        f = self.opener.open(req)
      File "/usr/lib/python2.7/urllib2.py", line 406, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 444, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 500: Internal Server Error

They didn't seem to recur, so we're hoping retrying helps.

Test Plan: Fingers crossed

Reviewers: chris

Reviewed By: chris

Differential Revision: http://phabricator.khanacademy.org/D9578