Give a better error message when github calls fail.
Summary:
Right now, I often get cron mail with this error for
"git_repos.add(repo['clone_url'])":
    TypeError: string indices must be integers

Clearly repo isn't what we are expecting (presumably it's a json
response with an error message instead).  This adds a try/except so we
can better report what the unexpected 'repo' looks like, and maybe
rewrite this code to give better error messages in the future.

Test Plan: Fingers crossed.

Reviewers: chris

Reviewed By: chris

Differential Revision: http://phabricator.khanacademy.org/D3936