Update gae_util.fix_sys_path() to avoid conflict w/bigquery package
When we installed the bigquery Python package to support querying BQ, we
accidentally broke some dashboard-scraping cron scripts because the
bigquery package is also under "google." and so import
"google.appengine" is now looking at the wrong module!

The failed (now fixed) traceback:

  Traceback (most recent call last):
    File "/home/ubuntu/internal-webserver/gae_dashboard/ka_report.py", line 31, in <module>
      import gae_dashboard_scrape
    File "/home/ubuntu/internal-webserver/gae_dashboard/gae_dashboard_scrape.py", line 33, in <module>
      import gae_dashboard_curl
    File "/home/ubuntu/internal-webserver/gae_dashboard/gae_dashboard_curl.py", line 32, in <module>
      from google.appengine.tools import appengine_rpc
  ImportError: No module named appengine.tools

Auditors: csilvers

Test Plan:
I updated the code on toby and wasn't emailed an error message the next
time the cron job ran.