Increase Sailthru API Client timeout
We've been getting this failure since quite sometime now.

(This happens while accessing the "blast" api with arguments start_date, end_date, status and limit.)
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/sailthru/sailthru_client.py", line 716, in api_get
return self._api_request(action, data, 'GET')
File "/usr/local/lib/python2.7/dist-packages/sailthru/sailthru_client.py", line 771, in _api_request
return self._http_request(action, self._prepare_json_payload(data), request_type, file_data)
File "/usr/local/lib/python2.7/dist-packages/sailthru/sailthru_client.py", line 777, in _http_request
timeout=self.timeout, retries=self.retries)
File "/usr/local/lib/python2.7/dist-packages/sailthru/sailthru_http.py", line 66, in sailthru_http_request
raise SailthruClientError(str(e))
sailthru.sailthru_error.SailthruClientError: HTTPSConnectionPool(host='api.sailthru.com (http://api.sailthru.com/) ', port=443): Max retries exceeded with url: /blast?json=%7B%22status%22%3A+%22sent%22%2C+%22limit%22%3A+0%2C+%22start_date%22%3A+%22January+1+2010%22%2C+%22end_date%22%3A+%22July+01+2018%22%7D&api_key=d18314df38560acfd14413cc89008485&sig=0635828b282ac25849750c53732fa361&format=json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.sailthru.com (http://api.sailthru.com/) ', port=443): Read timed out. (read timeout=20)",))
```

This commit increases the timeout from 20 to 40.

Test Plan: fingers crossed

Auditors: csilvers