Another exception type we need to catch.
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/local/frankenserver/python/lib/fancy_urllib/fancy_urllib/__init__.py", line 417, in do_open
    raise url_error
  URLError: <urlopen error [Errno 104] Connection reset by peer>

I guess the rule is that it only returns HTTPError when there's an
http response code.  OK.

Auditors: chris

Test plan:
Fingers crossed.